#set text(lang: "pt", region: "BR")
#set heading(numbering: "1.1")

// A introdução ocupará a seção 1 quando o restante do artigo for incorporado.
#counter(heading).update(1)

= Trabalhos relacionados

== Qualidade e falhas em pipelines de dados

Foidl et al. (#cite(<foidl2024>, form: "year")) investigam os fatores que comprometem a capacidade das _pipelines_ em processar dados corretamente e entregá-los com qualidade. Para compreender esses fatores e localizar os problemas relacionados aos dados, o estudo combina uma revisão multivocal da literatura, entrevistas com oito profissionais de engenharia de dados e análises de _issues_ do GitHub e publicações do Stack Overflow. A revisão resultou em uma taxonomia de 41 fatores, distribuídos entre aspectos dos dados, do desenvolvimento, da infraestrutura, do ciclo de vida e do processamento.

Na análise do GitHub, problemas de tipo representaram 33% das 100 _issues_ relacionadas a dados identificadas no conjunto final. Essas ocorrências apareceram principalmente nas etapas de limpeza, ingestão e integração. No Stack Overflow, integração e ingestão reuniram 47% dos tópicos discutidos, enquanto questões de compatibilidade formaram uma categoria adicional aos estágios usuais de processamento. Os autores indicam que a taxonomia pode orientar a identificação e a priorização de aspectos que prejudicam a qualidade das _pipelines_.

A pesquisa ajuda a delimitar o que uma estratégia de validação precisa observar, pois tipos, representação, caracteres e compatibilidade interferem na forma como os dados são recebidos e processados. Essa relação apoia a escolha de mudanças estruturais que serão avaliadas no TCC. O alcance do estudo, entretanto, permanece descritivo e genérico: são analisados relatos de desenvolvedores e projetos de software, sem o acompanhamento de versões históricas de uma base pública ou o teste de ferramentas de validação sob alterações controladas. Resta observar como esses problemas aparecem quando uma fonte pública muda sua estrutura ao longo do tempo, situação examinada pelo trabalho seguinte.

== Evolução de schema em dados públicos brasileiros

Yamanaka et al. (#cite(<yamanaka2024>, form: "year")) aproximam a discussão das mudanças que ocorrem quando uma fonte pública disponibiliza novas versões de seus dados. O estudo examina arquivos anuais do Censo Escolar brasileiro, publicados pelo Ministério da Educação e integrados ao Laboratório de Dados Educacionais. Alterações de nomes, adições e remoções de colunas dificultam a correspondência entre os arquivos e o _schema_ mantido pelo sistema. Os autores registram 416 mudanças e mostram que uma associação incorreta pode separar em duas colunas uma informação que apenas mudou de nome, preenchendo anos anteriores com valores nulos e comprometendo análises posteriores.

A pesquisa propõe uma metodologia estatística que compara a distribuição das colunas numéricas de versões consecutivas. São avaliados os testes Kolmogorov-Smirnov, Anderson-Darling, t de Welch e F. As sugestões são confrontadas com um _ground truth_ em dois cenários: o _Top 1_ considera a primeira coluna indicada, enquanto o _Top 3_ verifica se a correspondência correta aparece entre as três primeiras. O teste Kolmogorov-Smirnov obteve acurácia média de 84,7% no _Top 1_ e 89,7% no _Top 3_ na comparação com o ano anterior. Com o acúmulo dos anos anteriores, a acurácia _Top 1_ caiu para 74,4%.

O estudo mostra que a evolução estrutural de uma base pública pode ser examinada por quem integra os dados, sem depender dos nomes das colunas. Para este TCC, isso oferece um cenário próximo ao CNES e exemplos de mudanças capazes de afetar a continuidade de uma _pipeline_. A abordagem, contudo, restringe-se a atributos numéricos, mantém um especialista na escolha entre candidatos e não avalia Great Expectations, Pandera, Frictionless ou Soda Core. Com o problema estrutural delimitado, torna-se necessário compreender como ferramentas de qualidade transformam requisitos de validação e monitoramento em recursos disponíveis ao consumidor.

== Medição e monitoramento por ferramentas de qualidade

Ehrlinger e Wöß (#cite(<ehrlinger2022>, form: "year")) investigam como conceitos de medição e monitoramento de qualidade de dados aparecem nas ferramentas disponíveis. O estudo parte da distância entre as dimensões discutidas na literatura e as funções oferecidas na prática. Sua busca reuniu 667 ferramentas associadas à qualidade de dados. Após a aplicação de critérios de exclusão, 17 foram selecionadas e 13 puderam ser avaliadas, sendo oito comerciais e cinco _open-source_. A análise utiliza um catálogo de 43 requisitos sobre _data profiling_, medição de qualidade e monitoramento contínuo. As ferramentas foram instaladas e examinadas por dois pesquisadores com uma versão do banco Northwind.

A comparação mostrou ampla presença de funções básicas de _data profiling_ em uma única coluna, como contagem de valores nulos e identificação de tipos. Recursos envolvendo múltiplas colunas ou descoberta de dependências apareceram com menor frequência. Os autores também não encontraram uma ferramenta que implementasse um conjunto amplo das métricas propostas pela literatura para as principais dimensões de qualidade. Algumas métricas de acurácia dependiam de um conjunto de referência que nem sempre existe. O monitoramento automatizado variou entre as soluções e, nas ferramentas generalistas, apareceu frequentemente como recurso de versões comerciais.

Nesse contexto, o catálogo oferece critérios para avaliar regras de validação e recursos de monitoramento. Essa distinção é pertinente para um consumidor que acompanha uma fonte sem possuir uma base confiável para comparar os dados recebidos. O levantamento, contudo, retrata versões específicas das ferramentas e não inclui Great Expectations, Pandera, Frictionless ou Soda Core entre as soluções avaliadas. Também não testa versões históricas de dados públicos ou mudanças estruturais controladas. A visão geral oferecida pelo _survey_ deixa uma questão mais específica: quais verificações estão implementadas nas ferramentas _open-source_ atuais e como elas representam requisitos de _schema_?

== Funcionalidades de ferramentas open-source

Papastergios, Ehrlinger e Gounaris (#cite(<papastergios2026>, form: "year")) aprofundam a análise das ferramentas _open-source_ ao examinar como suas funcionalidades são implementadas. O estudo parte de um problema de terminologia: funções semelhantes recebem nomes diferentes nas ferramentas, enquanto um mesmo termo pode representar operações distintas. Para aproximar essas implementações das dimensões discutidas na literatura, os autores selecionam sete projetos ativos e de uso geral, entre eles Great Expectations e Soda Core. A documentação oficial e o código-fonte são examinados separadamente para cada ferramenta. Em seguida, funcionalidades equivalentes são reunidas, organizadas por finalidade e relacionadas a seis dimensões da ISO/IEC 25012.

O levantamento produz um catálogo de verificações de conformidade, distribuição, volume, cardinalidade, correlação e verificações orientadas a _machine learning_. Entre as funções ligadas ao _schema_ estão a conferência do número e da ordem das colunas, a presença de campos esperados, a ausência de campos inesperados e a validação de tipos. Os resultados mostram que nenhuma das sete ferramentas cobre todo o conjunto encontrado. Também indicam que a relação entre uma verificação concreta e uma dimensão de qualidade não é direta: uma mesma função pode contribuir para mais de uma dimensão, e uma dimensão depende de diferentes verificações.

O catálogo contribui para esta pesquisa ao relacionar mudanças estruturais a _checks_ que podem ser procurados durante a implementação do experimento. A presença de Great Expectations e Soda Core aproxima o _survey_ das ferramentas selecionadas, mas Pandera e Frictionless não fazem parte da análise. O trabalho também não executa um _benchmark_ entre as soluções. Sua comparação registra funcionalidades incorporadas, sem medir acurácia de detecção, falsos positivos, custo computacional ou esforço de configuração. Assim, o estudo descreve o que as ferramentas oferecem, mas não demonstra como elas se comportam quando recebem versões alteradas de uma base pública. Essa passagem da capacidade catalogada para o uso em dados governamentais aparece no trabalho seguinte, que seleciona Great Expectations e a aplica em duas situações reais.

== Avaliação de dados governamentais com Great Expectations

Oliveira et al. (#cite(<oliveira2023>, form: "year")) analisam a qualidade de dados governamentais de Minas Gerais utilizados em aplicações de licitações e despesas públicas. O problema investigado está nas inconsistências que podem afetar análises posteriores e que não são impedidas pelas restrições de integridade do _data warehouse_ empregado. Inicialmente, os autores comparam oito ferramentas _open-source_ segundo dez categorias de funcionalidades identificadas em suas documentações. Great Expectations foi a solução que melhor atendeu ao conjunto adotado, com parte das funções disponível de forma nativa e parte dependente de customização. A ferramenta foi então aplicada a dez tabelas reais mantidas em Apache Hive, divididas entre os dois domínios governamentais.

A avaliação combina _expectations_ nativas com regras desenvolvidas pelos autores em Python. As verificações tratam de valores nulos, unicidade, tipos, intervalos, expressões regulares e relações entre colunas. As regras customizadas examinam condições próprias do domínio, como a coerência entre valores financeiros e a ordem cronológica de datas. Os resultados apontaram valores fora de intervalos, tipos inconsistentes, duplicidades e violações de regras de negócio. O estudo também propõe o _Table Error Score_, uma medida que considera o tamanho da tabela, a proporção de verificações com falha e o percentual de valores inesperados para ordenar tabelas que exigem inspeção manual @oliveira2023.

A aplicação de Great Expectations em dados públicos brasileiros é o cenário mais próximo da pesquisa desenvolvida neste TCC. O trabalho mostra como regras definidas por quem utiliza os dados podem revelar inconsistências sem exigir alterações no sistema produtor. Entretanto, somente Great Expectations é executada nos estudos de caso; as outras ferramentas são comparadas por sua documentação. A pesquisa não acompanha mudanças de _schema_ entre versões, não utiliza defeitos estruturais controlados e não mede falsos positivos, falsos negativos, esforço de configuração ou custo computacional.

== Análise comparativa

Os cinco trabalhos observam partes diferentes de um mesmo percurso. Foidl et al. (#cite(<foidl2024>, form: "year")) investigam problemas que afetam a qualidade das _pipelines_. Yamanaka et al. (#cite(<yamanaka2024>, form: "year")) levam a discussão para versões de uma base pública brasileira e mostram como mudanças em colunas dificultam sua integração. Os _surveys_ examinam as ferramentas em outro nível: Ehrlinger e Wöß (#cite(<ehrlinger2022>, form: "year")) avaliam recursos de _data profiling_, medição e monitoramento, enquanto Papastergios, Ehrlinger e Gounaris (#cite(<papastergios2026>, form: "year")) identificam _checks_ no código-fonte. Oliveira et al. (#cite(<oliveira2023>, form: "year")) aplicam Great Expectations a dados governamentais após comparar oito soluções.

As diferenças de método impedem a comparação dos resultados por uma medida comum. Foidl et al. (#cite(<foidl2024>, form: "year")) combinam revisão, entrevistas e relatos de desenvolvedores para identificar causas e áreas problemáticas. Yamanaka et al. (#cite(<yamanaka2024>, form: "year")) realizam um experimento com _ground truth_ e medem a acurácia da correspondência de colunas. O _survey_ de 2022 usa um catálogo de requisitos e casos de teste, enquanto o de 2026 classifica funcionalidades e dimensões de qualidade sem medir desempenho. Oliveira et al. (#cite(<oliveira2023>, form: "year")) contam falhas de _expectations_ e valores inesperados em tabelas governamentais. Acurácia de correspondência, frequência de problemas, cobertura funcional e falhas de validação representam, portanto, resultados distintos.

A cobertura das ferramentas também varia. Ehrlinger e Wöß (#cite(<ehrlinger2022>, form: "year")) não incluem as quatro soluções escolhidas para este TCC. Papastergios, Ehrlinger e Gounaris (#cite(<papastergios2026>, form: "year")) examinam Great Expectations e Soda Core, mas não Pandera e Frictionless. Oliveira et al. (#cite(<oliveira2023>, form: "year")) aplicam somente Great Expectations, pois as demais ferramentas são comparadas por documentação. Foidl et al. (#cite(<foidl2024>, form: "year")) e Yamanaka et al. (#cite(<yamanaka2024>, form: "year")) não avaliam ferramentas de validação. Quanto às mudanças estruturais, Yamanaka et al. oferecem a evidência mais direta, embora trabalhem apenas com colunas numéricas e mantenham um especialista na escolha entre os candidatos. Os demais estudos tratam tipos, formatos, presença de colunas e compatibilidade como problemas ou _checks_, sem aplicar alterações equivalentes a ferramentas diferentes.

As pesquisas usam contextos, dados e critérios próprios, não adotam um protocolo experimental comum e não medem conjuntamente falsos positivos, falsos negativos, esforço de configuração e custo computacional. Os _surveys_ descrevem cobertura, mas não demonstram eficácia diante de versões alteradas. Os estudos empíricos se aproximam dos dados públicos ou das _pipelines_, porém não comparam as quatro ferramentas em condições equivalentes. Entre os cinco trabalhos analisados, permanece sem avaliação o comportamento de Great Expectations, Pandera, Frictionless e Soda Core diante das mesmas mudanças estruturais em versões do CNES. Essa oportunidade orienta o TCC para uma comparação controlada do lado consumidor, limitada à capacidade de detectar e sinalizar alterações sem pressupor cooperação ou garantias do produtor.

#bibliography("references.bib", title: [Referências], style: "associacao-brasileira-de-normas-tecnicas")
